ALTER TABLE projects ADD COLUMN IF NOT EXISTS repo_url VARCHAR(500);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS video_url VARCHAR(500);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS presentation_url VARCHAR(500);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS preview_photo_url VARCHAR(500);
